In [14]:
#list, dictionary, tuple, set

y = "Yamini"
b = "Kaushal"
print("hello my name is {} {}".format(y ,b))


hello my name is Yamini Kaushal


In [11]:
a = "adit"
print(f"my name is {a}")

my name is adit


In [15]:
len("Yamini")

6

In [18]:
#logical operators with boolean

True and False
True or True

True

In [19]:
not True

False

In [ ]:
#list is a mutable, hetereogeneous, ordered sequence of items
#list() is a built-in function used to create a new list object. It can be used to convert other iterable data types like tuples, strings, or sets into a list.

In [22]:
list()

[]

In [39]:
l = [1,"Hello", 56.4]
l

[1, 'Hello', 56.4]

In [40]:
l.append('Krish')
l

[1, 'Hello', 56.4, 'Krish']

In [50]:
#indexing
l[2]

'Mini'

In [43]:
l.insert(2,"Mini")

In [49]:
l

[1, 'Hello', 'Mini', 56.4, 'Krish', [4, 5], [4, 5]]

In [51]:
l.append([4,5])

In [52]:
l

[1, 'Hello', 'Mini', 56.4, 'Krish', [4, 5], [4, 5], [4, 5]]

In [54]:
l.extend([80, "Kumar"])
l


[1, 'Hello', 'Mini', 56.4, 'Krish', [4, 5], [4, 5], [4, 5], 80, 'Kumar']

In [58]:
l = [5, 20, 70]
sum(l)

95

In [59]:
l.pop()

70

In [60]:
l

[5, 20]

In [62]:
l.pop(0)
l

[20]

In [64]:
#list gets appended in itself that many times
l*2

[20, 20]

In [65]:
lst = [1,3,2,3,4,5,6,7]
max(lst)

7

In [66]:
min(lst)

1

In [67]:
lst.count(3)

2

In [68]:
len(lst)

8

In [69]:
lst.index(3)

1

In [72]:
#returns the index of first occurence of value, start and end range is optional. 4 here is value and 3, 7 are parameters
lst.index(4,3,7)

4

In [75]:
#Set is an unorder collection, iterable, mutable, no duplicates 

set_var = set()
print(set_var)
type(set_var)



set()


set

In [78]:
set_var = {1,2,3,4,4}
set_var

{1, 2, 3, 4}

In [84]:
set_var = {"Avenger", "Ironman","Hitman"}
set_var.add("Wonderwoman")
set_var

{'Avenger', 'Hitman', 'Ironman', 'Wonderwoman'}

In [105]:
set1 = {"Avenger", "Ironman","Hitman"}
set2 = {"Avenger", "Ironman","Hitman","Hulk"}

#difference - doesnt change set 2


set2.difference(set1)



{'Hulk'}

In [108]:
set2.union(set1)


{'Avenger', 'Hitman', 'Hulk', 'Ironman'}

In [101]:
set2.intersection(set1)

set2.intersection_update(set1)
set2

{'Avenger', 'Hitman', 'Ironman'}

In [103]:
#difference update changes set 2
set2.difference_update(set1)

#due to update here its giving empty set
set2

set()

In [123]:
#dictionaries 
#unordered, indexed by keys, changeable, has key value pairs

dic = {}
type(dic)

dict

In [133]:
my_dic = {1:"Yami", 2:"Mona", 3:"Preeti"}
my_dic

{1: 'Yami', 2: 'Mona', 3: 'Preeti'}

In [134]:
type(dict())

dict

In [135]:
#access items values based on keys

my_dic[1]

'Yami'

In [136]:
#will print keys
for x in my_dic:
    print(x)

1
2
3


In [137]:
for x in my_dic.values():
    print(x)

Yami
Mona
Preeti


In [138]:
for x in my_dic.items():
    print(x)

(1, 'Yami')
(2, 'Mona')
(3, 'Preeti')


In [139]:
#adding items in dictionaries 
my_dic[4] = "Ajay"
my_dic

{1: 'Yami', 2: 'Mona', 3: 'Preeti', 4: 'Ajay'}

In [140]:
my_dic[1] = "Yamini"
my_dic

{1: 'Yamini', 2: 'Mona', 3: 'Preeti', 4: 'Ajay'}

In [145]:
 #nested dictionary
car1 = {'Mercedes': 1960}
car2 = {'Audi': 1970}
car3= {'Ambassador': 1980}

car_models = {'car1': car1, 'car2': car2, 'car3': car3}
car_models
    
    
    

{'car1': {'Mercedes': 1960},
 'car2': {'Audi': 1970},
 'car3': {'Ambassador': 1980}}

In [148]:
car_models['car1']['Mercedes']

1960

In [152]:
#Tuples - immutable, indexed

my_tuple = tuple()
type(my_tuple)

tuple

In [154]:
my_tuple = ("Krish", "Aditi")
my_tuple

('Krish', 'Aditi')

In [155]:
my_tuple[0]

'Krish'

In [159]:
#cant change items in tuple but can change whole tuple

my_tuple = ("Amisha", "Mansi")
my_tuple

('Amisha', 'Mansi')

In [160]:
#count and index - inbuilt function

my_tuple.count('Amisha')

1

In [161]:
my_tuple.index('Mansi')

1

In [3]:
#Numpy - array processing package, provides high-performance multidimensional array object and tools for working with array

#Array is a data structure stores same data type values

#import numpy
import numpy as np 



In [4]:
my_list = [1,2,3,4,5]

arr = np.array(my_list)
type(arr)

numpy.ndarray

In [182]:
#one dimensional array
arr

array([1, 2, 3, 4, 5])

In [184]:
#will give no of elements for 1-D array
arr.shape

(5,)

In [188]:
#multidimensional array - nested array from nested list

my_list1 = [1,2,3,4,5]
my_list2 = [4,6,7,8,2]
my_list3 = [3,5,6,7,2]

arr = np.array([my_list1, my_list2,my_list3])
arr


array([[1, 2, 3, 4, 5],
       [4, 6, 7, 8, 2],
       [3, 5, 6, 7, 2]])

In [192]:
#will give no of rows and columns in 2-D array
arr.shape

(3, 5)

In [199]:
#return an array containing same data with new shape
#make sure no of elements is same while reshaping, same count as shape while reshaping

In [198]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 4],
       [6, 7, 8],
       [2, 3, 5],
       [6, 7, 2]])

In [202]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 4, 6, 7, 8, 2, 3, 5, 6, 7, 2]])

In [21]:
#Indexing 

arr = np.array([1,2,3,4])
#get in range, excluding end values
arr[0:3]

array([1, 2, 3])

In [19]:
#get exact value
arr[2]

3

In [20]:

my_list1 = [1,2,3,4,5]
my_list2 = [4,6,7,8,2]
my_list3 = [3,5,6,7,2]

arr = np.array([my_list1, my_list2,my_list3])
arr


array([[1, 2, 3, 4, 5],
       [4, 6, 7, 8, 2],
       [3, 5, 6, 7, 2]])

In [11]:
#can get exact value
arr[0,2]

3

In [14]:
#can get in a range, excluding end points
arr[0:2, 0:4]

array([[1, 2, 3, 4],
       [4, 6, 7, 8]])

In [16]:
#includes all rows and columns
arr[:, :]

array([[1, 2, 3, 4, 5],
       [4, 6, 7, 8, 2],
       [3, 5, 6, 7, 2]])

In [17]:
arr[1:, 2:4]

array([[7, 8],
       [6, 7]])

In [25]:
arr[1, 1:4]

array([6, 7, 8])

In [40]:
#will take it as an endpoint exclusive
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [29]:
#excludes end value
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [31]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [38]:
#generates evenly spaced numbers over a specified interval
arr, step = np.linspace(1,10,20, retstep = True)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [67]:
arr = np.arange(5)
arr

#copy function and boradcasting

array([0, 1, 2, 3, 4])

In [69]:
arr[1:3] = 50

In [70]:
arr

array([ 0, 50, 50,  3,  4])

In [71]:
#this assignment will change the original array arr when changes done in arr1
#it uses referencing
#shallow copy
arr1 = arr
arr1

array([ 0, 50, 50,  3,  4])

In [72]:
arr1[1] = 20
arr

array([ 0, 20, 50,  3,  4])

In [80]:
arr = np.arange(5)
arr
#deep copy, separate memory
#copy() method is used to create a deep copy of an array. A deep copy means that a new array object is created, and its elements are the same as the original array. Modifying the copy will not affect the original array,

arr2 = arr.copy()
arr2[1] = 50
arr

array([0, 1, 2, 3, 4])

In [81]:
arr2

array([ 0, 50,  2,  3,  4])

In [90]:
#I can extract array values by giving specific condition
#EDA used in

arr2%2==0
arr2[arr2%2==0]

array([ 0, 50,  2,  4])

In [100]:
#operations on array 
val = 2
arr2

array([ 0, 50,  2,  3,  4])

In [94]:
arr2*val

array([  0, 100,   4,   6,   8])

In [97]:
arr2+val

array([ 2, 52,  4,  5,  6])

In [99]:
arr2/2

array([ 0. , 25. ,  1. ,  1.5,  2. ])

In [101]:
arr2<2

array([ True, False, False, False, False])

In [102]:
#create arrays and reshape

np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
#returns array of ones, takes shape - 1D, 2D, 3D
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [109]:
np.ones((2,3), dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
#random distribution
# 0 to 1 exclusive
np.random.rand(3,3)

array([[0.99127719, 0.64600908, 0.61957989],
       [0.04944597, 0.16630785, 0.81780621],
       [0.89764552, 0.91826269, 0.33273279]])

In [112]:
np.random.randn(4,4)

array([[ 0.36799437,  0.08087905, -0.74762059, -0.56908624],
       [ 1.20853555, -0.69382975,  0.07689502,  0.80555   ],
       [ 0.49808828,  0.50373179, -0.82053312,  0.31640884],
       [ 0.51127323, -0.28372566, -0.11812611,  1.19426421]])

In [121]:
np.random.randint(0,100,10).reshape(2,5)

array([[27, 60, 96,  0, 95],
       [30, 60, 88, 87, 61]])

In [118]:
#random floating numbers between 0 to 1 exclusive
np.random.random_sample((3,4))

array([[0.22418104, 0.06699198, 0.97975871, 0.31767483],
       [0.43229666, 0.15151367, 0.69354504, 0.66409174],
       [0.6296362 , 0.5048317 , 0.68166183, 0.58948719]])

In [4]:
#PANDAS 

import pandas as pd 
import numpy as np 

#data is 2D, index, column
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index = ['Row1', 'Row2', 'Row3', 'Row4','Row5'], columns= ['Col1', 'Col2', 'Col3', 'Col4']) 


In [2]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [3]:
df.to_csv("Test_csv")

In [4]:
#Accessing elements

# loc and iloc 
#loc uses index labes iloc uses integer indices
#Loc includes end while iloc excludes

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

In [17]:
#DataFrame - More than one row and more than one column, has atleast more than one row and atleast more than one column
#Series - One row or one column

#returns series

type(df.loc['Row1'])

pandas.core.series.Series

In [12]:
#provide range of indexes
#returns dataframe
df.iloc[:, :]

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [15]:
df.iloc[0:2, 0:2]

Col1  Col2
Row1     0     1
Row2     4     5

In [16]:
type(df.iloc[0:2, 0:2])

pandas.core.frame.DataFrame

In [49]:
df.iloc[0:2,0:1]

Col1
Row1     0
Row2     4

In [22]:
type(df.iloc[0:2,2])

pandas.core.series.Series

In [25]:
df['Col1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int32

In [26]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [31]:
df.loc['Row1', 'Col1']

0

In [34]:
df.loc['Row1','Col1']

0

In [43]:
df.loc['Row1':'Row4', 'Col1':'Col4']

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15

In [38]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [41]:
df.iloc[[0,3]]

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row4    12    13    14    15

In [42]:
df.iloc[[0,3], [0,3]]

Col1  Col4
Row1     0     3
Row4    12    15

In [50]:
df.iloc[:, 1:]

Col2  Col3  Col4
Row1     1     2     3
Row2     5     6     7
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [52]:
#convert dataframes into array

df.iloc[:, 1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [55]:
df.iloc[:, 1:].values.shape

(5, 3)

In [57]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [58]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [63]:
#count of values present in a column, occurence count

df['Col1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Col1, dtype: int64

In [66]:
#list of unique values
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

In [72]:
type(df['Col1'])

pandas.core.series.Series

In [89]:
#send in a form of list
df.loc['Row1',['Col1','Col3']]

Col1    0
Col3    2
Name: Row1, dtype: int32

In [92]:
df[['Col1', 'Col2']]

Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
Row5    16    17

In [105]:
df = pd.read_csv(r"C:\Users\anjali\Downloads\mercedes-benz-greener-manufacturing\train.csv\train.csv", sep =',')

In [106]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [104]:
#only float and int are taken into consideration
#categorical features are skipped
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [107]:
#Get unique category counts

df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [109]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [5]:
#to read csv or any data stored in string format use StringIO
#data in string to df
from io import StringIO

In [12]:
data = ('col1, col2, col3 \n'
         'x,y,1 \n'
         'a,b,2 \n'
          'c,d,3')

In [8]:
type(data)

str

In [121]:
df = pd.read_csv(StringIO(data))

In [122]:
df.head()

col1  col2   col3 
0    x     y       1
1    a     b       2
2    c     d       3

In [16]:
#read from specific columns

#df = pd.read_csv(StringIO(data), usecols = ['col1', 'col2'])

df.to_csv('Testing.csv')

In [17]:
#specifying column data type

data = ('a,b,c,d \n'
       '1,2,3,4 \n'
        '5,6,7,8 \n'
       '9,10,11')

In [18]:
print(data)

a,b,c,d 
1,2,3,4 
5,6,7,8 
9,10,11


In [29]:
df = pd.read_csv(StringIO(data), dtype = object)
df

a   b   c   d 
0  1   2   3   4 
1  5   6   7   8 
2  9  10  11  NaN

In [26]:
type(df['a'][0])

str

In [27]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [54]:

data = ('a,b,c,d \n'
       '1,2,3,4 \n'
        '5,6,7,8 \n'
       '9,10,11,12')

df = pd.read_csv(StringIO(data), dtype = float)
df['a']

0    1.0
1    5.0
2    9.0
Name: a, dtype: float64

In [55]:
#making different columns have different datatype

df = pd.read_csv(StringIO(data), dtype = {'a': int, 'b':float, 'c':int, 'd': int})
df

a     b   c  d 
0  1   2.0   3   4
1  5   6.0   7   8
2  9  10.0  11  12

In [61]:
type(df['a'][1])

numpy.int32

In [67]:
# index columns and training delimiters

data = ('index, a, b, c \n'
       '4, apple, bat, 5.7 \n'
       '8, orange,cow, 10')

df = pd.read_csv(StringIO(data), index_col = 0)
df

a     b    c 
index                     
4        apple   bat   5.7
8       orange   cow  10.0

In [81]:
data = ('a,b,c \n'
       '4,apple,bat \n'
       '8, orange, cow')

#index_col will not make any col index automatically
pd.read_csv(StringIO(data), index_col = False, usecols = ['a','b'])

a        b
0  4    apple
1  8   orange

In [84]:
#quoting and escape characters, useful in NLP

data = 'a,b \n"hello, \\"Bob\\", nice to see you",5'

pd.read_csv(StringIO(data), escapechar = '\\')



a  b 
0  hello, "Bob", nice to see you   5

In [87]:
#url to csv

#df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep = '\t')


In [99]:
 #Read Json to CSV 

data = '{"employee": "James", "email": "james@gmail.com", "job_profile": [{"title1": "Team lead", "title2": "Developer" }]}' 
df1 = pd.read_json(data)
df1

employee            email                                     job_profile
0    James  james@gmail.com  {'title1': 'Team lead', 'title2': 'Developer'}

In [94]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header = None)

In [95]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [96]:
#convert json to csv 


df.to_csv('wine.csv')

In [100]:
df1.to_json()

'{"employee":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team lead","title2":"Developer"}}}'

In [101]:
df1.to_json(orient = "records")

'[{"employee":"James","email":"james@gmail.com","job_profile":{"title1":"Team lead","title2":"Developer"}}]'

In [115]:
#Reading HTML content
#web scraping


#The match="Mobile Network Codes" parameter indicates that only tables with a title containing the string "Mobile Network Codes" will be extracted from the HTML page.



# !pip install html5lib 
# import html5lib

# url = "https://en.wikipedia.org/wiki/Mobile_country_code"
# dfs = pd.read_html(url, match = "Mobile Network Codes", header = 0)
# dfs[0]

In [118]:
df_excel = pd.read_excel(r"C:\Users\anjali\Downloads\Excel_Sample.xlsx", header = None)

In [119]:
df_excel.head()

0   1   2   3
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21

In [124]:
#pickling 


#pickling helps save object's datastructures in binary or file format for reuse. Use cPickle to save data structure to disk
#used in ML
#preprocessing, convert to pickle so that restarting kernel doesnt make performing all instructions again
df_excel.to_pickle('pickling')
df = pd.read_pickle('pickling')
df.head()

0   1   2   3
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21